"""empty message

Revision ID: 254b178e6af2
Revises: 5f7fa0c2b1da
Create Date: 2019-10-17 20:17:15.870049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254b178e6af2'
down_revision = '5f7fa0c2b1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('APIid', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('Fuzzy', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('car_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('end_time_fuzzy', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('start_time_fuzzy', sa.String(), nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('environment_id')
        batch_op.drop_column('password')
        batch_op.drop_column('name')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('environment_id', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('start_time_fuzzy')
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time_fuzzy')
        batch_op.drop_column('end_time')
        batch_op.drop_column('duration')
        batch_op.drop_column('car_id')
        batch_op.drop_column('Fuzzy')
        batch_op.drop_column('APIid')

    # ### end Alembic commands ###
