"""empty message

Revision ID: 83203ec8b613
Revises: f950c9d090eb
Create Date: 2019-10-18 03:45:20.046338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83203ec8b613'
down_revision = 'f950c9d090eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_assignment_model',
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('achievement_id', 'user_email')
    )
    op.create_table('achievement_model',
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level_req', sa.Integer(), nullable=True),
    sa.Column('level_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_table('experience_model',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('charger_exp', sa.Integer(), nullable=False),
    sa.Column('car_sharer_exp', sa.Integer(), nullable=False),
    sa.Column('eco_driver_exp', sa.Integer(), nullable=False),
    sa.Column('reliability_exp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    with op.batch_alter_table('booking_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fuzzy', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_column('start_time_fuzzy')
        batch_op.drop_column('end_time_fuzzy')
        batch_op.drop_column('Fuzzy')
        batch_op.drop_column('APIid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('APIid', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('Fuzzy', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('end_time_fuzzy', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('start_time_fuzzy', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('id')
        batch_op.drop_column('fuzzy')
        batch_op.drop_column('distance')

    op.drop_table('experience_model')
    op.drop_table('achievement_model')
    op.drop_table('achievement_assignment_model')
    # ### end Alembic commands ###
