"""empty message

Revision ID: dc101cdc124c
Revises: 6c87bed46efa
Create Date: 2019-10-17 20:46:26.092074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc101cdc124c'
down_revision = '6c87bed46efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_model',
    sa.Column('APIid', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('Fuzzy', sa.String(), nullable=False),
    sa.Column('car_id', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('start_time_fuzzy', sa.String(), nullable=True),
    sa.Column('end_time_fuzzy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('APIid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_model')
    # ### end Alembic commands ###
